import{a as w,S as P,i as n}from"./assets/vendor-BkC4bTqC.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(e){if(e.ep)return;e.ep=!0;const a=t(e);fetch(e.href,a)}})();async function h(o,r=1,t=15){const s=Math.max(t,15);return(await w.get("https://pixabay.com/api/",{params:{key:"55065193-391623a3c41ad24a1105f24d8",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:s}})).data}let q=new P(".gallery-item",{captionDelay:250});const m=document.querySelector("#gallery"),p=document.querySelector(".load-more");function g(o){const r=o.map(t=>`
  <a href="${t.largeImageURL}" class="gallery-item">
    <img src="${t.webformatURL}" alt="${t.tags}" />
    <div class="info">
      <p><b>Likes:</b> ${t.likes}</p>
      <p><b>Views:</b> ${t.views}</p>
      <p><b>Comments:</b> ${t.comments}</p>
      <p><b>Downloads:</b> ${t.downloads}</p>
    </div>
  </a>
`).join("");m.innerHTML=r,q.refresh()}function S(){m.innerHTML=""}function y(){document.querySelector(".loader").classList.remove("hidden")}function L(){document.querySelector(".loader").classList.add("hidden")}function b(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}const M=document.querySelector(".search-form");document.querySelector(".gallery");const v=document.querySelector(".load-more");let c,i=1,u=15,f=0;function C(){v.disabled=!1}M.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements.searchText.value.trim(),!!c){i=1,S(),d(),y();try{const r=await h(c,i,u),{hits:t,totalHits:s}=r;if(!t||t.length===0){n.error({message:"No images found. Please try a different search query.",CaretPosition:"topRight"});return}f=Math.ceil(s/u),g(t),i<f?b():n.error({message:"Youve reached the end of search results.",CaretPosition:"topRight"})}catch{n.error({message:"Something went wrong. Pleasevtry again",CaretPosition:"topRight"})}finally{L()}}});v.addEventListener("click",async()=>{i+=1,d(),y();try{const{hits:o}=await h(c,i,u);if(o.length===0){n.info({message:"Were sorry, but youve reached the end of search results.",CaretPosition:"topRight"}),d();return}g(o);const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),i>=f&&(b(),n.info({message:"We're  sorry, but youve reached the end of search results",CaretPosition:"topRight"}))}catch{n.info({message:"error",CaretPosition:"topRight"})}finally{C(),L()}});
//# sourceMappingURL=index.js.map
