import{a as g,S as L}from"./assets/vendor-DMAHcxl-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(e){if(e.ep)return;e.ep=!0;const a=t(e);fetch(e.href,a)}})();async function u(r,o=1,t=15){const n=Math.max(t,15);return(await g.get("https://pixabay.com/api/",{params:{key:"55065193-391623a3c41ad24a1105f24d8",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:n}})).data}let b=new L(".gallery-item",{captionDelay:250});const f=document.querySelector("#gallery");function p(r){const o=r.map(t=>`
  <a href="${t.largeImageURL}" class="gallery-item">
    <img src="${t.webformatURL}" alt="${t.tags}" />
    <div class="info">
      <p><b>Likes:</b> ${t.likes}</p>
      <p><b>Views:</b> ${t.views}</p>
      <p><b>Comments:</b> ${t.comments}</p>
      <p><b>Downloads:</b> ${t.downloads}</p>
    </div>
  </a>
`).join("");f.innerHTML=o,b.refresh()}function v(){f.innerHTML=""}function m(){document.querySelector(".loader").classList.remove("hidden")}function y(){document.querySelector(".loader").classList.add("hidden")}function w(){loadMoreBtn.classList.remove("hidden")}function h(){loadMoreBtn.classList.add("hidden")}const q=document.querySelector(".search-form");document.querySelector(".gallery");const M=document.querySelector(".load-more");let i,s=1,l=15,d=0;q.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.target.elements.searchText.value.trim(),!i){s=1,v(),h();return}m();try{const o=await u(i,s,l),{hits:t,totalHits:n}=o;if(!t||t.length===0){alert("No images found. Please try a different search query.");return}d=Math.ceil(n/l),p(t),s<d?w():alert("You've reached the end of search results.")}catch(o){console.error("Error fetching images:",o)}finally{y()}});M.addEventListener("click",async()=>{s+=1,m();try{const r=await u(i,s,l);p(r.hits||r),s>=d&&h()}catch(r){console.error(r)}finally{y()}});
//# sourceMappingURL=index.js.map
