import{a as v,S as P,i}from"./assets/vendor-BkC4bTqC.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();async function p(r,a=1,t=15){const s=Math.max(t,15);return(await v.get("https://pixabay.com/api/",{params:{key:"55065193-391623a3c41ad24a1105f24d8",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:s}})).data}let w=new P(".gallery-item",{captionDelay:250});const h=document.querySelector("#gallery"),y=document.querySelector(".load-more");function g(r){const a=r.map(t=>`
  <a href="${t.largeImageURL}" class="gallery-item">
    <img src="${t.webformatURL}" alt="${t.tags}" />
    <div class="info">
      <p><b>Likes:</b> ${t.likes}</p>
      <p><b>Views:</b> ${t.views}</p>
      <p><b>Comments:</b> ${t.comments}</p>
      <p><b>Downloads:</b> ${t.downloads}</p>
    </div>
  </a>
`).join("");h.innerHTML=a,w.refresh()}function q(){h.innerHTML=""}function L(){document.querySelector(".loader").classList.remove("hidden")}function b(){document.querySelector(".loader").classList.add("hidden")}function M(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}const S=document.querySelector(".search-form");document.querySelector(".gallery");const m=document.querySelector(".load-more");let c,n=1,u=15,f=0;function $(){m.disabled=!0}function B(){m.disabled=!1}S.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.target.elements.searchText.value.trim(),!!c){n=1,q(),d(),L();try{const a=await p(c,n,u),{hits:t,totalHits:s}=a;if(!t||t.length===0){i.error({message:"No images found. Please try a different search query.",CaretPosition:"topRight"});return}f=Math.ceil(s/u),g(t),n<f?M():i.error({message:"Youve reached the end of search results.",CaretPosition:"topRight"})}catch{i.error({message:"error.message",CaretPosition:"topRight"})}finally{b()}}});m.addEventListener("click",async()=>{n+=1,$(),L();try{const{hits:r}=await p(c,n,u);if(r.length===0){d();return}g(r),n>=f&&(d(),i.info({message:"We're  sorry, but youve reached the end of search results",CaretPosition:"topRight"}))}catch{i.info({messege:"error",CaretPosition:"topRight"})}finally{B(),b()}});
//# sourceMappingURL=index.js.map
